### ISSUE TITLE
Uploading issue

### ISSUE THREAD

**Issue by MDHowe4** [labsyspharm/cycif_viewer#132]
I have run into an inconsistent bug where if the Dataset Name field has been used previously, even if not accessible in Data Sources, will fail to upload and hang. Here is an error message where I used the name `test` for the Dataset Name field while uploading:

```
ERROR: C:\Users\Desktop\data\test\cell.tif: Output file already exists, aborting.
ERROR:waitress:Exception when servicing <waitress.channel.HTTPChannel connected 127.0.0.1:54373 at 0x231d7124640>
Traceback (most recent call last):
  File "waitress\task.py", line 84, in handler_thread
  File "waitress\channel.py", line 428, in service
  File "waitress\task.py", line 168, in service
  File "waitress\task.py", line 434, in execute
  File "flask\app.py", line 2548, in __call__
  File "flask\app.py", line 2525, in wsgi_app
  File "flask\app.py", line 1820, in full_dispatch_request
  File "flask\app.py", line 1796, in dispatch_request
  File "minerva_analysis\server\routes\import_routes.py", line 259, in upload_file_page
    label_info = data_model.convertOmeTiff(labelFile, channelFilePath=channelFile, dataDirectory=file_path, isLabelImg=True)
  File "minerva_analysis\server\models\data_model.py", line 902, in convertOmeTiff
    pyramid_assemble.main(py_args=args)
  File "minerva_analysis\server\utils\pyramid_assemble.py", line 167, in main
    error(out_path, "Output file already exists, aborting.")
  File "minerva_analysis\server\utils\pyramid_assemble.py", line 132, in error
    sys.exit(1)
SystemExit: 1
Percentage: 50 1 2 Converting Segmentation Mask
Percentage: 50 1 2 Converting Segmentation Mask
Percentage: 50 1 2 Converting Segmentation Mask
Percentage: 50 1 2 Converting Segmentation Mask
```
This can be overcome by using a completely unique identifier each time which results in a successful upload, but does not seem like intended behavior

**Comment by boyden** [comment]
There will be a data folder where you run the software. You can try to delete the old dataset name and try it again, which solve my similar problem.
