### ISSUE TITLE
libvips and opencv-python errors

### ISSUE THREAD

**Issue by thejohnhoffer** [labsyspharm/cycif_viewer#3]
I have conda 4.8.2 on MacOS 10.12.6.

I run the following command to create an env
`conda env create -n cycif_viewer -f requirements.yml python=3.7`

It appears to work successfully. I then run `conda activate cycif_viewer`.

After I run this command to start the server:
```
~/opt/anaconda3/envs/cycif_viewer/bin/python -m flask run
```

I get the following error with `libvips`:

```
Traceback (most recent call last):
  File "/Users/John/opt/anaconda3/envs/cycif_viewer/lib/python3.7/site-packages/pyvips/__init__.py", line 19, in <module>
    import _libvips
ModuleNotFoundError: No module named '_libvips'

During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/Users/John/opt/anaconda3/envs/cycif_viewer/lib/python3.7/runpy.py", line 193, in _run_module_as_main                    
    "__main__", mod_spec)                          
  File "/Users/John/opt/anaconda3/envs/cycif_viewer/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/John/opt/anaconda3/envs/cycif_viewer/lib/python3.7/site-packages/flask/__main__.py", line 15, in <module>
    main(as_module=True)
  File "/Users/John/opt/anaconda3/envs/cycif_viewer/lib/python3.7/site-packages/flask/cli.py", line 967, in main 
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/Users/John/opt/anaconda3/envs/cycif_viewer/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/Users/John/opt/anaconda3/envs/cycif_viewer/lib/python3.7/site-packages/click/core.py", line 782, in main 
    rv = self.invoke(ctx)
  File "/Users/John/opt/anaconda3/envs/cycif_viewer/lib/python3.7/site-packages/click/core.py", line 1259, in invoke                           
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/John/opt/anaconda3/envs/cycif_viewer/lib/python3.7/site-packages/click/core.py", line 1066, in invoke 
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/John/opt/anaconda3/envs/cycif_viewer/lib/python3.7/site-packages/click/core.py", line 610, in invoke 
    return callback(*args, **kwargs) 
  File "/Users/John/opt/anaconda3/envs/cycif_viewer/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func 
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/John/opt/anaconda3/envs/cycif_viewer/lib/python3.7/site-packages/click/core.py", line 610, in invoke 
    return callback(*args, **kwargs)
  File "/Users/John/opt/anaconda3/envs/cycif_viewer/lib/python3.7/site-packages/flask/cli.py", line 848, in run_command 
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/Users/John/opt/anaconda3/envs/cycif_viewer/lib/python3.7/site-packages/flask/cli.py", line 305, in __init__ 
    self._load_unlocked()
  File "/Users/John/opt/anaconda3/envs/cycif_viewer/lib/python3.7/site-packages/flask/cli.py", line 330, in _load_unlocked 
    self._app = rv = self.loader()
  File "/Users/John/opt/anaconda3/envs/cycif_viewer/lib/python3.7/site-packages/flask/cli.py", line 392, in load_app 
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "/Users/John/opt/anaconda3/envs/cycif_viewer/lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app 
    __import__(module_name)
  File "/Users/John/projects/cycif_viewer/app.py", line 2, in <module> 
    from server import mostFrequentLongestSubstring, fullConversion, pre_normalization, dataFilter
  File "/Users/John/projects/cycif_viewer/server/fullConversion.py", line 12, in <module> 
    import pyvips
  File "/Users/John/opt/anaconda3/envs/cycif_viewer/lib/python3.7/site-packages/pyvips/__init__.py", line 71, in <module> 
    vips_lib = ffi.dlopen(_vips_libname)
  File "/Users/John/opt/anaconda3/envs/cycif_viewer/lib/python3.7/site-packages/cffi/api.py", line 150, in dlopen 
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/Users/John/opt/anaconda3/envs/cycif_viewer/lib/python3.7/site-packages/cffi/api.py", line 832, in _make_ffi_library 
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/Users/John/opt/anaconda3/envs/cycif_viewer/lib/python3.7/site-packages/cffi/api.py", line 827, in _load_backend_lib 
    raise OSError(msg)
OSError: cannot load library 'libvips.42.dylib': dlopen(libvips.42.dylib, 2): image not found.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'l ibvips.42.dylib'
```

I then run `conda install -c conda-forge libvips`. The command executes successfully.

I try once again to run 
```
~/opt/anaconda3/envs/cycif_viewer/bin/python -m flask run
```

But I see the following `opencv-python` error message:

```
Error: While importing "app", an ImportError was raised:

Traceback (most recent call last):
  File "/Users/John/opt/anaconda3/envs/cycif_viewer/lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/Users/John/projects/cycif_viewer/app.py", line 2, in <module>
    from server import mostFrequentLongestSubstring, fullConversion, pre_normalization, dataFilter
  File "/Users/John/projects/cycif_viewer/server/fullConversion.py", line 14, in <module>
    import cv2
  File "/Users/John/opt/anaconda3/envs/cycif_viewer/lib/python3.7/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: dlopen(/Users/John/opt/anaconda3/envs/cycif_viewer/lib/python3.7/site-packages/cv2/cv2.cpython-37m-darwin.so, 2): Symbol not found: _inflateValidate
  Referenced from: /Users/John/opt/anaconda3/envs/cycif_viewer/lib/python3.7/site-packages/cv2/.dylibs/libpng16.16.dylib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libz.1.dylib
 in /Users/John/opt/anaconda3/envs/cycif_viewer/lib/python3.7/site-packages/cv2/.dylibs/libpng16.16.dylib
```
 
My opencv-python version is 4.2.0.34.

I then run
```
~/opt/anaconda3/envs/cycif_viewer/bin/pip uninstall opencv-python
~/opt/anaconda3/envs/cycif_viewer/bin/pip install opencv-python
```
Now my opencv-python version is 4.4.0.40
After that, the command ` ~/opt/anaconda3/envs/cycif_viewer/bin/python -m flask run` works as expected.

**Comment by simonwarchol** [comment]
Hey @johnhoffer, just removed the pyvips dependency from the requirements file, and added another step in the install process per the `README`. Let me play around a bit with opencv 4.4.0.40 to make sure it doesn't break anything else before I made that update as well.
Appreciate the feedback

**Comment by simonwarchol** [comment]
Ok I've updated the requirements.yml for OpenCv 4.4*. Closing this issue
